### ISSUE TITLE
TP

### ISSUE THREAD

**Issue by Slashgear** [PolytechLyon/4a-isi3-tp2-2016-2017-groupe-1-martin_joymangul#1]
⚠️ L'uml est pas visible dans le rapport

👍 ⚠️ Alors c'est pas mal ce petit Visitable, après Si vous ajouter un autre type de Visiteur il faudra rajouter un nouveau `accept` dans chaque élément du graph.. C'est ce qu'on voulait éviter en utilisant le pattern Visiteur. Il est surement possible de conserver qu'un seul accept pout tout les types de visites.

❓ La priorité de la multiplication ça marche ?

**Comment by GaetanMartin** [comment]
L'image de l'UML était incorrecte, c'est corrigé !
La priorité de la multiplication a été testé sur plusieurs exemples
L'implantation des accepts dans les visitables a été revu, on a 2 solutions (cf les branches)

**Comment by Slashgear** [comment]
Nice les deux solutions, c'est déjà mieux 👍
